package com.api.csis3275_backend.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.Getter;

@Entity
public class Administrator {
    @Id
    private int autoGeneratedId;

    @Getter
    private int adminId;
    @Getter
    private String username;
    @Getter
    private String password;

    public Administrator() {}
    public Administrator(int adminId, String username, String password) {
        adminId = adminId;
        username = username;
        password = password;
    }

    public void setAdminId(int adminId) {
        this.adminId = adminId;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}
